const BIN_ID="6a9b0f99da38895dfe399c73",MASTER_KEY="$2a$10$hmXdJoo8tCS.xYXR1iTV9O8YoeagMRUQmupeveyJUy.p81/e2y/7S",ACCESS_KEY="$2a$10$pqInp3O8CbNngOF0Y2rFW.oI0uk/xVUoGuGjUgpwFMFgRlhY8pAGS",API_URL=`https://api.jsonbin.io/v3/b/${BIN_ID}`;
const ADMIN_USER="INVESTOR20",ADMIN_PASS="202020";let data=null,idle=120,timer=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function fetchBin(){const r=await fetch(`${API_URL}/latest?_=${Date.now()}`,{cache:'no-store',headers:{'X-Master-Key':MASTER_KEY,'X-Access-Key':ACCESS_KEY}});if(!r.ok)throw Error('Load failed');const j=await r.json();data=j.record||{};data.users=Array.isArray(data.users)?data.users:[];data.products=Array.isArray(data.products)?data.products:[];data.withdrawals=Array.isArray(data.withdrawals)?data.withdrawals:[];data.paymentSubmissions=Array.isArray(data.paymentSubmissions)?data.paymentSubmissions:[];data.settings=data.settings||{};return data}
async function saveBin(){const r=await fetch(API_URL,{method:'PUT',headers:{'Content-Type':'application/json','X-Master-Key':MASTER_KEY,'X-Access-Key':ACCESS_KEY},body:JSON.stringify(data)});if(!r.ok)throw Error('Save failed')}
function toast(t){const x=document.getElementById('toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2600)}
function showSection(name){document.querySelectorAll('.section').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.section===name));const s=document.getElementById('section-'+name);if(s)s.classList.add('active');const title={overview:'Dashboard',settings:'Settings',products:'Products',customers:'Customers',uploads:'Payment Uploads',withdrawals:'Withdrawals'}[name]||'Dashboard';document.getElementById('sectionTitle').textContent=title;renderSection(name)}
function fillSettings(){const s=data.settings||{};['bankName','accountName','bankAccount','whatsapp','telegram','telegramChannel'].forEach(k=>{const e=document.getElementById(k);if(e)e.value=s[k]||''})}
function renderSection(name){if(!data)return;if(name==='overview'){document.getElementById('statUsers').textContent=data.users.length;document.getElementById('statUploads').textContent=data.paymentSubmissions.length;document.getElementById('statWithdrawals').textContent=data.withdrawals.length}if(name==='settings')fillSettings();if(name==='products'){const b=document.getElementById('productsList');b.innerHTML=data.products.length?data.products.map((p,i)=>`<div class="product"><strong>${esc(p.badge||['🥉','🥈','🥇','💎','👑'][i%5])} ${esc(p.name||'Plan')}</strong><div class="muted" style="margin-top:6px">${esc(p.desc||'')}</div><div style="margin-top:8px">Investment: <b>₦${Number(p.price||0).toLocaleString()}</b> &nbsp; Profit: <b>₦${Number(p.profit||0).toLocaleString()}</b></div></div>`).join(''):'<div class="empty">No products</div>'}if(name==='customers'){const b=document.getElementById('usersBody');b.innerHTML=data.users.length?data.users.map(u=>`<tr><td>${esc(u.fullName||'—')}</td><td>${esc(u.email||'—')}</td><td>${esc(u.id||'—')}</td><td>${esc(u.referralCode||'—')}</td><td>${u.joined?new Date(u.joined).toLocaleDateString():'—'}</td><td>${esc(u.status||'active')}</td><td>₦${Number(u.balance||0).toLocaleString()}</td></tr>`).join(''):'<tr><td colspan="7" class="empty">No customers</td></tr>'}if(name==='uploads'){const b=document.getElementById('uploadsList');b.innerHTML=data.paymentSubmissions.length?data.paymentSubmissions.map(p=>`<article class="proof"><b>${esc(p.productName||'Product')}</b><div class="proof-meta"><b>${esc(p.fullName||'')}</b><br>${esc(p.email||'')}<br>Amount: ₦${Number(p.amount||0).toLocaleString()}<br>Date: ${p.date?new Date(p.date).toLocaleString():'—'}<br>Status: <span class="status">${esc(p.status||'pending')}</span></div>${p.imageData?`<img src="${p.imageData}" alt="Payment proof">`: '<div class="empty">No image attached</div>'}<button class="btn outline" onclick="markProof('${String(p.id||'').replace(/'/g,"\\'")}','reviewed')">Mark Reviewed</button></article>`).join(''):'<div class="empty">No payment uploads yet</div>'}if(name==='withdrawals'){const b=document.getElementById('withdrawalsBody');b.innerHTML=data.withdrawals.length?data.withdrawals.map(w=>`<tr><td>${esc(w.fullName||w.email||'—')}</td><td>₦${Number(w.amount||0).toLocaleString()}</td><td>${esc(w.status||'pending')}</td><td>${w.date?new Date(w.date).toLocaleString():'—'}</td></tr>`).join(''):'<tr><td colspan="4" class="empty">No withdrawal requests</td></tr>'}}
async function refreshAll(){try{await fetchBin();renderSection(document.querySelector('.nav button.active')?.dataset.section||'overview');toast('Data refreshed')}catch(e){toast('Unable to refresh')}}
async function saveSettings(){data.settings={...data.settings,bankName:document.getElementById('bankName').value.trim(),accountName:document.getElementById('accountName').value.trim(),bankAccount:document.getElementById('bankAccount').value.trim(),whatsapp:document.getElementById('whatsapp').value.trim(),telegram:document.getElementById('telegram').value.trim(),telegramChannel:document.getElementById('telegramChannel').value.trim()};try{await saveBin();toast('Settings saved')}catch(e){toast('Save failed')}}
function uniqueCode(used){let c;do{c='GF-'+Math.random().toString(36).slice(2,8).toUpperCase()}while(used.has(c));used.add(c);return c}
async function repairReferralCodes(){const used=new Set();data.users.forEach(u=>{const c=String(u.referralCode||'').toUpperCase();if(c)used.add(c)});const seen=new Set();data.users.forEach(u=>{const c=String(u.referralCode||'').toUpperCase();if(!c||seen.has(c)){u.referralCode=uniqueCode(used)}seen.add(u.referralCode)});try{await saveBin();renderSection('customers');toast('Referral codes repaired')}catch(e){toast('Repair failed')}}
async function markProof(id,status){const p=data.paymentSubmissions.find(x=>String(x.id)===String(id));if(!p)return;p.status=status;try{await saveBin();renderSection('uploads');toast('Upload marked reviewed')}catch(e){toast('Update failed')}}
function logout(){sessionStorage.removeItem('gf_admin_logged');location.reload()}
function startIdle(){clearInterval(timer);idle=120;timer=setInterval(()=>{idle--;document.getElementById('idleTimer').textContent=`Idle ${Math.floor(idle/60)}:${String(idle%60).padStart(2,'0')}`;if(idle<=0)logout()},1000);['click','keydown','touchstart','mousemove','scroll'].forEach(e=>document.addEventListener(e,()=>idle=120,{passive:true}))}
async function openAdmin(){document.getElementById('loginScreen').style.display='none';document.getElementById('adminApp').style.display='block';try{await fetchBin();renderSection('overview');startIdle()}catch(e){toast('Unable to load data')}}
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('.nav button').forEach(b=>b.addEventListener('click',()=>showSection(b.dataset.section)));document.getElementById('loginForm').addEventListener('submit',async e=>{e.preventDefault();const u=document.getElementById('username').value.trim(),p=document.getElementById('password').value;if(u===ADMIN_USER&&p===ADMIN_PASS){sessionStorage.setItem('gf_admin_logged','true');await openAdmin()}else document.getElementById('loginError').textContent='Invalid username or password'});if(sessionStorage.getItem('gf_admin_logged')==='true')openAdmin()})
